### PR TITLE
Fix compile error when default features are off

### LINKED ISSUE #383: Compile error with default features turned off
## Version
Main

## What you did

Turned off default features for LWIM
```
[dependencies]
bevy = { version = "0.11.2", default-features = false}
leafwing-input-manager = { git = "https://github.com/Leafwing-Studios/leafwing-input-manager.git", default-features = false}
```

## What you expected to happen

The window to be created and the app run normally

## What actually happened

A compile error is printed in the terminal

## Additional information
Log:
```
failed to resolve: use of undeclared type `UiSystem`
   --> leafwing-input-manager/src/plugin.rs:118:32
    |
118 |                         .after(UiSystem::Focus)
```

This error is introduced in #375.

### PR DESCRIPTION
**Pull request by 100-TomatoJuice**
Closes #383 
I tested minimal, ui_driven_actions, and bindings_menu to test different features. They all worked as expected.

### CODE REVIEW

File: src/plugin.rs [hunk 1]
```diff
@@ -133,6 +129,18 @@ impl<A: Actionlike> Plugin for InputManagerPlugin<A> {
                         .after(UiSystem::Focus)
                         .after(InputSystem),
                 );
+
+                app.add_systems(
```
Comment (alice-i-cecile) [inline src/plugin.rs:133]: I think this will be cleaner if we move it above the feature-gated code.

Comment (100-TomatoJuice) [reply src/plugin.rs]: I moved it above the `configue_sets()` to pair it with the other `add_systems()`
